//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodamGroceryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroceryItem
    {
        public int ID { get; set; }
        public string ItemType { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> ItemPurchasedPrice { get; set; }
        public Nullable<decimal> ItemRetailPrice { get; set; }
        public Nullable<int> ItemQuantity { get; set; }
    }
}
